[CI] Pinned the Rake version to 10.x to prevent clashes with the Yard gem
The builds have been failing on Travis with:

      cd /home/travis/build/elastic/elasticsearch-ruby/elasticsearch && unset BUNDLE_GEMFILE && bundle exec rake test:unit
      rm -rf tmp/reports
      rake aborted!
      NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000002872ec0>